import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:m_shop/core/widgets/section_card.dart';
import 'package:m_shop/features/dashboard/domain/models/dashboard_models.dart';
import 'package:m_shop/features/profile/presentation/widgets/components/profile_models.dart';

class ProfileChartsGrid extends StatelessWidget {
  const ProfileChartsGrid({super.key, required this.financialReports, required this.production, required this.markets, required this.currencies, required this.summary});

  final List<FinancialReport> financialReports;
  final List<ProductionPoint> production;
  final List<CompanyMarket> markets;
  final List<CurrencyPoint> currencies;
  final ProfileSummary summary;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (context, constraints) {
      final wide = constraints.maxWidth > 1100;
      final width = wide ? (constraints.maxWidth - 18) / 2 : constraints.maxWidth;
      return Wrap(spacing: 18, runSpacing: 18, children: [
        SizedBox(width: width, child: _ChartCard(title: 'جراف الإيراد الخطي', subtitle: 'حركة الإيراد بين الفترات.', painter: _RevenueLinePainter(financialReports), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف الربح المساحي', subtitle: 'اتجاه الربحية بشكل ناعم.', painter: _ProfitAreaPainter(financialReports), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف الإنتاج بالأعمدة', subtitle: 'الفعلي مقابل المستهدف.', painter: _ProductionBarsPainter(production), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف الأسواق الدائري', subtitle: 'توزيع البيع حسب الأسواق.', painter: _MarketsDonutPainter(markets), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف العملات', subtitle: 'متابعة العملات البيعية الرئيسية.', painter: _CurrencyBarsPainter(currencies), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف السيولة التدفقي', subtitle: 'صورة سريعة لتدفق النقد.', painter: _CashFlowPainter(summary), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف الفقاعات للمخاطر', subtitle: 'فقاعات تعكس الضغط المالي والتشغيلي.', painter: _BubbleRiskPainter(summary), height: 280)),
        SizedBox(width: width, child: _ChartCard(title: 'جراف الرادار الاستراتيجي', subtitle: 'صورة كلية لصاحب القرار.', painter: _OwnerRadarPainter(summary), height: 280)),
      ]);
    });
  }
}

class _ChartCard extends StatelessWidget { const _ChartCard({required this.title, required this.subtitle, required this.painter, required this.height}); final String title; final String subtitle; final CustomPainter painter; final double height; @override Widget build(BuildContext context) { return SectionCard(title: title, subtitle: subtitle, child: SizedBox(height: height, child: CustomPaint(painter: painter, size: Size.infinite))); } }

class _RevenueLinePainter extends CustomPainter { const _RevenueLinePainter(this.reports); final List<FinancialReport> reports; @override void paint(Canvas canvas, Size size) { final list = reports.isEmpty ? const [FinancialReport(period: 'شهر', income: 100000, expenses: 70000, profit: 30000)] : reports; const l=40.0,r=18.0,t=18.0,b=30.0; final w=size.width-l-r,h=size.height-t-b; final maxV=list.map((e)=>e.income).reduce(math.max)+10000; final points=<Offset>[]; final slot=list.length<=1?w:w/(list.length-1); for (var i=0;i<list.length;i++){ final x=l+slot*i; final y=t+h-((list[i].income/maxV)*h); points.add(Offset(x,y)); final tp=TextPainter(text: TextSpan(text:list[i].period, style: const TextStyle(color: Color(0xFF677C76), fontSize: 10, fontWeight: FontWeight.w700)), textDirection: TextDirection.rtl)..layout(); tp.paint(canvas, Offset(x-tp.width/2,size.height-20)); } final path=_smooth(points); canvas.drawPath(path, Paint()..color=const Color(0xFF2563EB)..style=PaintingStyle.stroke..strokeWidth=3); for(final p in points){ canvas.drawCircle(p,4.5,Paint()..color=const Color(0xFF2563EB)); } } Path _smooth(List<Offset> points){ if(points.length==1)return Path()..addOval(Rect.fromCircle(center: points.first,radius:1)); final path=Path()..moveTo(points.first.dx, points.first.dy); for(var i=1;i<points.length;i++){ final prev=points[i-1]; final cur=points[i]; final mid=(prev.dx+cur.dx)/2; path.cubicTo(mid, prev.dy, mid, cur.dy, cur.dx, cur.dy);} return path;} @override bool shouldRepaint(covariant _RevenueLinePainter oldDelegate)=>oldDelegate.reports!=reports; }
class _ProfitAreaPainter extends CustomPainter { const _ProfitAreaPainter(this.reports); final List<FinancialReport> reports; @override void paint(Canvas canvas, Size size){ final list=reports.isEmpty?const [FinancialReport(period:'شهر', income:100000, expenses:70000, profit:30000)]:reports; const l=40.0,r=18.0,t=18.0,b=30.0; final w=size.width-l-r,h=size.height-t-b; final maxV=list.map((e)=>e.profit).reduce(math.max)+5000; final pts=<Offset>[]; final slot=list.length<=1?w:w/(list.length-1); for(var i=0;i<list.length;i++){ final x=l+slot*i; final y=t+h-((list[i].profit/maxV)*h); pts.add(Offset(x,y)); } final line=_smooth(pts); final area=Path.from(line)..lineTo(pts.last.dx,t+h)..lineTo(pts.first.dx,t+h)..close(); canvas.drawPath(area, Paint()..shader=const LinearGradient(begin: Alignment.topCenter,end: Alignment.bottomCenter,colors:[Color(0x6616A34A),Color(0x0516A34A)]).createShader(Rect.fromLTWH(l,t,w,h))); canvas.drawPath(line, Paint()..color=const Color(0xFF16A34A)..style=PaintingStyle.stroke..strokeWidth=3);} Path _smooth(List<Offset> points){ if(points.length==1)return Path()..addOval(Rect.fromCircle(center: points.first,radius:1)); final path=Path()..moveTo(points.first.dx, points.first.dy); for(var i=1;i<points.length;i++){ final prev=points[i-1]; final cur=points[i]; final mid=(prev.dx+cur.dx)/2; path.cubicTo(mid, prev.dy, mid, cur.dy, cur.dx, cur.dy);} return path;} @override bool shouldRepaint(covariant _ProfitAreaPainter oldDelegate)=>oldDelegate.reports!=reports; }
class _ProductionBarsPainter extends CustomPainter { const _ProductionBarsPainter(this.production); final List<ProductionPoint> production; @override void paint(Canvas canvas, Size size){ final list=production.isEmpty?const [ProductionPoint(label:'أ', actual:70, target:84)]:production.take(5).toList(); const l=22.0,r=18.0,t=18.0,b=34.0; final w=size.width-l-r,h=size.height-t-b; final barW=math.min(30.0,w/math.max(1,list.length*2.2)); final gap=(w-(barW*2*list.length))/math.max(1,list.length); final maxV=list.expand((e)=>[e.actual,e.target]).reduce(math.max)+10; for(var i=0;i<list.length;i++){ final base=l+gap/2+i*((barW*2)+gap); final ah=h*(list[i].actual/maxV); final th=h*(list[i].target/maxV); canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(base,t+h-ah,barW,ah), const Radius.circular(10)), Paint()..color=const Color(0xFF0F766E)); canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(base+barW+6,t+h-th,barW,th), const Radius.circular(10)), Paint()..color=const Color(0xFF94A3B8)); } } @override bool shouldRepaint(covariant _ProductionBarsPainter oldDelegate)=>oldDelegate.production!=production; }
class _MarketsDonutPainter extends CustomPainter { const _MarketsDonutPainter(this.markets); final List<CompanyMarket> markets; @override void paint(Canvas canvas, Size size){ final center=Offset(size.width*0.36,size.height*0.5); final rect=Rect.fromCircle(center:center,radius:76); final colors=[const Color(0xFF0F766E),const Color(0xFF2563EB),const Color(0xFF16A34A),const Color(0xFFF59E0B),const Color(0xFF7C3AED)]; var start=-math.pi/2; for(var i=0;i<markets.length;i++){ final sweep=(markets[i].share*math.pi*2).toDouble(); canvas.drawArc(rect,start,sweep,false,Paint()..color=colors[i%colors.length]..style=PaintingStyle.stroke..strokeWidth=26..strokeCap=StrokeCap.round); start+=sweep; } final tp=TextPainter(text: const TextSpan(text:'أسواق
البيع', style: TextStyle(color: Color(0xFF111827), fontSize: 16, fontWeight: FontWeight.w900)), textAlign: TextAlign.center, textDirection: TextDirection.rtl)..layout(); tp.paint(canvas, Offset(center.dx-tp.width/2, center.dy-tp.height/2)); } @override bool shouldRepaint(covariant _MarketsDonutPainter oldDelegate)=>oldDelegate.markets!=markets; }
class _CurrencyBarsPainter extends CustomPainter { const _CurrencyBarsPainter(this.points); final List<CurrencyPoint> points; @override void paint(Canvas canvas, Size size){ const l=24.0,r=18.0,t=18.0,b=34.0; final w=size.width-l-r,h=size.height-t-b; final list=points; final maxV=list.map((e)=>e.value).reduce(math.max)+5; final barW=math.min(40.0,w/math.max(1,list.length*1.8)); final gap=(w-(barW*list.length))/math.max(1,list.length); for(var i=0;i<list.length;i++){ final x=l+gap/2+i*(barW+gap); final bh=h*(list[i].value/maxV); final accent=list[i].change>=0?const Color(0xFF2563EB):const Color(0xFFDC2626); canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(x,t+h-bh,barW,bh), const Radius.circular(12)), Paint()..color=accent); final lb=TextPainter(text: TextSpan(text:list[i].code, style: const TextStyle(color: Color(0xFF111827), fontSize: 10, fontWeight: FontWeight.w800)), textDirection: TextDirection.rtl)..layout(); lb.paint(canvas, Offset(x+(barW-lb.width)/2,size.height-20)); } } @override bool shouldRepaint(covariant _CurrencyBarsPainter oldDelegate)=>oldDelegate.points!=points; }
class _CashFlowPainter extends CustomPainter { const _CashFlowPainter(this.summary); final ProfileSummary summary; @override void paint(Canvas canvas, Size size){ const left=24.0; final points=[summary.availableCash*0.62, summary.totalExpenses*0.38, summary.totalProfit*0.52, summary.availableCash*0.74]; final labels=['دخل','مصروف','ربح','سيولة']; final maxV=points.reduce(math.max)+1000; for(var i=0;i<points.length;i++){ final x=left+i*70; final h=(size.height-60)*(points[i]/maxV); canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(x,size.height-34-h,44,h), const Radius.circular(12)), Paint()..color=i.isEven?const Color(0xFF0F766E):const Color(0xFF16A34A)); final tp=TextPainter(text: TextSpan(text:labels[i], style: const TextStyle(color: Color(0xFF111827), fontSize: 10, fontWeight: FontWeight.w800)), textDirection: TextDirection.rtl)..layout(); tp.paint(canvas, Offset(x+(44-tp.width)/2,size.height-22)); } } @override bool shouldRepaint(covariant _CashFlowPainter oldDelegate)=>oldDelegate.summary!=summary; }
class _BubbleRiskPainter extends CustomPainter { const _BubbleRiskPainter(this.summary); final ProfileSummary summary; @override void paint(Canvas canvas, Size size){ final bubbles=[(Offset(size.width*0.28,size.height*0.42), 44.0, const Color(0xFFDC2626)),(Offset(size.width*0.56,size.height*0.36), 32.0, const Color(0xFFF59E0B)),(Offset(size.width*0.46,size.height*0.62), 54.0, const Color(0xFF2563EB)),(Offset(size.width*0.72,size.height*0.58), 26.0, const Color(0xFF16A34A))]; for(final bubble in bubbles){ canvas.drawCircle(bubble.$1, bubble.$2, Paint()..color=bubble.$3.withValues(alpha: 0.22)); canvas.drawCircle(bubble.$1, bubble.$2, Paint()..color=bubble.$3.withValues(alpha: 0.72)..style=PaintingStyle.stroke..strokeWidth=2); } } @override bool shouldRepaint(covariant _BubbleRiskPainter oldDelegate)=>oldDelegate.summary!=summary; }
class _OwnerRadarPainter extends CustomPainter { const _OwnerRadarPainter(this.summary); final ProfileSummary summary; @override void paint(Canvas canvas, Size size){ final center=Offset(size.width*0.5,size.height*0.5); final radius=math.min(size.width,size.height)*0.28; final productionRatio=summary.totalTarget == 0 ? 0.0 : (summary.totalProduction/summary.totalTarget).clamp(0.0,1.0).toDouble(); final vals=[productionRatio, summary.netMargin.clamp(0.0,1.0).toDouble(), (1-(summary.alertCount/6)).clamp(0.0,1.0).toDouble(), (summary.availableCash/(summary.totalExpenses+1)).clamp(0.0,1.0).toDouble(), 0.82, 0.76]; for(var ring=1; ring<=4; ring++){ final rr=radius*ring/4; final p=Path(); for(var i=0;i<6;i++){ final a=-math.pi/2+(math.pi*2*i/6); final pt=Offset(center.dx+math.cos(a)*rr, center.dy+math.sin(a)*rr); if(i==0){p.moveTo(pt.dx,pt.dy);}else{p.lineTo(pt.dx,pt.dy);} } p.close(); canvas.drawPath(p, Paint()..color=const Color(0xFFDCE8E4)..style=PaintingStyle.stroke);} final data=Path(); for(var i=0;i<6;i++){ final a=-math.pi/2+(math.pi*2*i/6); final pt=Offset(center.dx+math.cos(a)*radius*vals[i], center.dy+math.sin(a)*radius*vals[i]); if(i==0){data.moveTo(pt.dx,pt.dy);}else{data.lineTo(pt.dx,pt.dy);} } data.close(); canvas.drawPath(data, Paint()..color=const Color(0x330F766E)); canvas.drawPath(data, Paint()..color=const Color(0xFF0F766E)..style=PaintingStyle.stroke..strokeWidth=2.4);} @override bool shouldRepaint(covariant _OwnerRadarPainter oldDelegate)=>oldDelegate.summary!=summary; }
