import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:m_shop/core/widgets/section_card.dart';
import 'package:m_shop/features/users/presentation/widgets/components/users_models.dart';

class UsersChartsGrid extends StatelessWidget {
  const UsersChartsGrid({super.key, required this.profiles, required this.summary});

  final List<WorkerProfile> profiles;
  final UsersSummary summary;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (context, constraints) {
      final wide = constraints.maxWidth > 1100;
      final width = wide ? (constraints.maxWidth - 18) / 2 : constraints.maxWidth;
      return Wrap(
        spacing: 18,
        runSpacing: 18,
        children: [
          SizedBox(width: width, child: _AreaChartCard(profiles: profiles)),
          SizedBox(width: width, child: _RoleDonutCard(profiles: profiles)),
          SizedBox(width: constraints.maxWidth, child: _SalaryBarsCard(profiles: profiles)),
        ],
      );
    });
  }
}

class _AreaChartCard extends StatelessWidget { const _AreaChartCard({required this.profiles}); final List<WorkerProfile> profiles; @override Widget build(BuildContext context) { return SectionCard(title: 'جراف أداء العمال', subtitle: 'منحنى يوضح مستوى الأداء للمستخدمين الأساسيين.', child: SizedBox(height: 300, child: CustomPaint(painter: _PerformanceAreaPainter(profiles), size: Size.infinite))); } }
class _RoleDonutCard extends StatelessWidget { const _RoleDonutCard({required this.profiles}); final List<WorkerProfile> profiles; @override Widget build(BuildContext context) { return SectionCard(title: 'جراف توزيع الصلاحيات', subtitle: 'قراءة دائرية لتوزيع الأدوار والصلاحيات داخل الفريق.', child: SizedBox(height: 300, child: CustomPaint(painter: _RoleDonutPainter(profiles), size: Size.infinite))); } }
class _SalaryBarsCard extends StatelessWidget { const _SalaryBarsCard({required this.profiles}); final List<WorkerProfile> profiles; @override Widget build(BuildContext context) { return SectionCard(title: 'جراف الأجور ومناطق العمل', subtitle: 'أعمدة توضح الأجور مع أسماء المستخدمين ومكان العمل الحالي.', child: SizedBox(height: 320, child: CustomPaint(painter: _SalaryBarPainter(profiles), size: Size.infinite))); } }

class _PerformanceAreaPainter extends CustomPainter { const _PerformanceAreaPainter(this.profiles); final List<WorkerProfile> profiles; @override void paint(Canvas canvas, Size size) { final list = profiles.take(5).toList(); const left = 44.0, right = 18.0, top = 18.0, bottom = 34.0; final width = size.width - left - right; final height = size.height - top - bottom; final points = <Offset>[]; final slot = list.length <= 1 ? width : width / (list.length - 1); for (var i = 0; i < 5; i++) { final y = top + height * i / 4; canvas.drawLine(Offset(left, y), Offset(size.width - right, y), Paint()..color = const Color(0xFFDCE8E4)); } for (var i = 0; i < list.length; i++) { final x = left + slot * i; final y = top + height - (height * list[i].performance.clamp(0.0, 1.0)); points.add(Offset(x, y)); final label = TextPainter(text: TextSpan(text: list[i].user.name.split(' ').first, style: const TextStyle(color: Color(0xFF677C76), fontSize: 10, fontWeight: FontWeight.w700)), textDirection: TextDirection.rtl)..layout(); label.paint(canvas, Offset(x - label.width / 2, size.height - 22)); } if (points.isEmpty) return; final line = _smooth(points); final area = Path.from(line)..lineTo(points.last.dx, top + height)..lineTo(points.first.dx, top + height)..close(); canvas.drawPath(area, Paint()..shader = const LinearGradient(begin: Alignment.topCenter, end: Alignment.bottomCenter, colors: [Color(0x660F766E), Color(0x050F766E)]).createShader(Rect.fromLTWH(left, top, width, height))); canvas.drawPath(line, Paint()..color = const Color(0xFF0F766E)..style = PaintingStyle.stroke..strokeWidth = 3.2); for (final point in points) { canvas.drawCircle(point, 5, Paint()..color = const Color(0xFF0F766E)); canvas.drawCircle(point, 5, Paint()..color = Colors.white..style = PaintingStyle.stroke..strokeWidth = 2); } } Path _smooth(List<Offset> points) { if (points.length == 1) return Path()..addOval(Rect.fromCircle(center: points.first, radius: 1)); final path = Path()..moveTo(points.first.dx, points.first.dy); for (var i = 1; i < points.length; i++) { final prev = points[i - 1]; final current = points[i]; final middle = (prev.dx + current.dx) / 2; path.cubicTo(middle, prev.dy, middle, current.dy, current.dx, current.dy); } return path; } @override bool shouldRepaint(covariant _PerformanceAreaPainter oldDelegate) => oldDelegate.profiles != profiles; }

class _RoleDonutPainter extends CustomPainter { const _RoleDonutPainter(this.profiles); final List<WorkerProfile> profiles; @override void paint(Canvas canvas, Size size) { final manager = profiles.where((e) => e.user.role.toLowerCase().contains('manager')).length.toDouble(); final supervisor = profiles.where((e) => e.user.role.toLowerCase().contains('supervisor')).length.toDouble(); final worker = profiles.where((e) => e.user.role.toLowerCase().contains('worker')).length.toDouble(); final total = math.max(1.0, manager + supervisor + worker); final values = [manager, supervisor, worker]; final labels = ['إدارة', 'إشراف', 'عمال']; final colors = [const Color(0xFF7C3AED), const Color(0xFF2563EB), const Color(0xFF0F766E)]; final center = Offset(size.width * 0.35, size.height * 0.5); final rect = Rect.fromCircle(center: center, radius: 82); var start = -math.pi / 2; for (var i = 0; i < values.length; i++) { final sweep = ((values[i] / total) * math.pi * 2).toDouble(); canvas.drawArc(rect, start, sweep, false, Paint()..color = colors[i]..style = PaintingStyle.stroke..strokeWidth = 28..strokeCap = StrokeCap.round); start += sweep; } final inner = TextPainter(text: TextSpan(text: '${profiles.length}\nمستخدم', style: const TextStyle(color: Color(0xFF111827), fontSize: 16, fontWeight: FontWeight.w900)), textAlign: TextAlign.center, textDirection: TextDirection.rtl)..layout(); inner.paint(canvas, Offset(center.dx - inner.width / 2, center.dy - inner.height / 2)); final legendX = size.width * 0.62; for (var i = 0; i < labels.length; i++) { final y = 80.0 + i * 50; canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(legendX, y + 3, 16, 16), const Radius.circular(6)), Paint()..color = colors[i]); final title = TextPainter(text: TextSpan(text: labels[i], style: const TextStyle(color: Color(0xFF111827), fontSize: 12, fontWeight: FontWeight.w800)), textDirection: TextDirection.rtl)..layout(); title.paint(canvas, Offset(legendX + 24, y)); final sub = TextPainter(text: TextSpan(text: values[i].round().toString(), style: const TextStyle(color: Color(0xFF667B75), fontSize: 11, fontWeight: FontWeight.w700)), textDirection: TextDirection.rtl)..layout(); sub.paint(canvas, Offset(legendX + 24, y + 18)); } } @override bool shouldRepaint(covariant _RoleDonutPainter oldDelegate) => oldDelegate.profiles != profiles; }

class _SalaryBarPainter extends CustomPainter { const _SalaryBarPainter(this.profiles); final List<WorkerProfile> profiles; @override void paint(Canvas canvas, Size size) { final list = profiles.take(6).toList(); if (list.isEmpty) return; const left = 24.0, right = 18.0, top = 18.0, bottom = 48.0; final width = size.width - left - right; final height = size.height - top - bottom; final maxSalary = list.map((e) => e.salary).reduce(math.max) + 800; final barWidth = math.min(52.0, width / math.max(1, list.length * 1.5)); final gap = (width - (barWidth * list.length)) / math.max(1, list.length); canvas.drawLine(Offset(left, top + height), Offset(size.width - right, top + height), Paint()..color = const Color(0xFFDCE8E4)); for (var i = 0; i < list.length; i++) { final x = left + gap / 2 + i * (barWidth + gap); final h = height * (list[i].salary / maxSalary); final rect = RRect.fromRectAndRadius(Rect.fromLTWH(x, top + height - h, barWidth, h), const Radius.circular(16)); canvas.drawRRect(rect, Paint()..color = list[i].accent); final salary = TextPainter(text: TextSpan(text: '${list[i].salary.round()}', style: TextStyle(color: list[i].accent, fontSize: 10, fontWeight: FontWeight.w800)), textDirection: TextDirection.rtl)..layout(); salary.paint(canvas, Offset(x + (barWidth - salary.width) / 2, top + height - h - 16)); final label = TextPainter(text: TextSpan(text: list[i].user.name.split(' ').first, style: const TextStyle(color: Color(0xFF111827), fontSize: 10, fontWeight: FontWeight.w700)), textDirection: TextDirection.rtl)..layout(maxWidth: 70); label.paint(canvas, Offset(x - ((70 - barWidth) / 2), size.height - 30)); final area = TextPainter(text: TextSpan(text: list[i].workArea, style: const TextStyle(color: Color(0xFF667B75), fontSize: 9, fontWeight: FontWeight.w600)), textDirection: TextDirection.rtl)..layout(maxWidth: 80); area.paint(canvas, Offset(x - ((80 - barWidth) / 2), size.height - 16)); } } @override bool shouldRepaint(covariant _SalaryBarPainter oldDelegate) => oldDelegate.profiles != profiles; }
