name: mazid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  liquid_swipe: ^3.1.0
  particles_flutter: ^1.0.1
  wave: ^0.2.2
  lottie: ^3.3.1
  video_player: ^2.10.0
  chewie: ^1.12.1

  supabase_flutter: ^2.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  animated_text_kit: ^4.2.3
  intl_phone_field: ^3.2.0
  curved_navigation_bar: ^1.0.6
  meta: ^1.16.0
  shared_preferences: ^2.5.3

  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.0.1  
  camera: ^0.11.2
  http: ^1.5.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cloud_firestore: ^6.0.1
  provider: ^6.1.5+1
  sensors_plus: ^6.1.2
  font_awesome_flutter: ^10.9.1
  shelf: ^1.4.2
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

dependency_overrides:
  analyzer: ">=6.0.0 <6.9.0"

flutter:
  uses-material-design: true

  assets:
    - asset/icon/iconimage.jpg
    - asset/animation/intro1animation.json
    - asset/animation/intro2.json
    - asset/animation/intro3.json
    - asset/image/sell-used-electronics.jpg
    - asset/image/offer50.png
    - asset/image/download.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon/iconimage.jpg"
